
angle_rules = dict()
angle_rules[('NL', 'NL')] = 'NL'
angle_rules[('NL', 'NM')] = 'NL'
angle_rules[('NL', 'NS')] = 'NL'
angle_rules[('NL', 'ZE')] = 'NL'
angle_rules[('NL', 'PS')] = 'NL'
angle_rules[('NL', 'PM')] = 'NM'
angle_rules[('NL', 'PL')] = 'ZE'

angle_rules[('NM', 'NL')] = 'NL'
angle_rules[('NM', 'NM')] = 'NL'
angle_rules[('NM', 'NS')] = 'NL'
angle_rules[('NM', 'ZE')] = 'NL'
angle_rules[('NM', 'PS')] = 'NM'
angle_rules[('NM', 'PM')] = 'ZE'
angle_rules[('NM', 'PL')] = 'PM'

angle_rules[('NS', 'NL')] = 'NL'
angle_rules[('NS', 'NM')] = 'NL'
angle_rules[('NS', 'NS')] = 'NL'
angle_rules[('NS', 'ZE')] = 'NM'
angle_rules[('NS', 'PS')] = 'ZE'
angle_rules[('NS', 'PM')] = 'PM'
angle_rules[('NS', 'PL')] = 'PB'

angle_rules[('ZE', 'NL')] = 'NL'
angle_rules[('ZE', 'NM')] = 'NL'
angle_rules[('ZE', 'NS')] = 'NM'
angle_rules[('ZE', 'ZE')] = 'ZE'
angle_rules[('ZE', 'PS')] = 'PM'
angle_rules[('ZE', 'PM')] = 'PL'
angle_rules[('ZE', 'PL')] = 'PL'

angle_rules[('PS', 'NL')] = 'NL'
angle_rules[('PS', 'NM')] = 'NM'
angle_rules[('PS', 'NS')] = 'ZE'
angle_rules[('PS', 'ZE')] = 'PM'
angle_rules[('PS', 'PS')] = 'PL'
angle_rules[('PS', 'PM')] = 'PL'
angle_rules[('PS', 'PL')] = 'PL'

angle_rules[('PM', 'NL')] = 'NM'
angle_rules[('PM', 'NM')] = 'ZE'
angle_rules[('PM', 'NS')] = 'PM'
angle_rules[('PM', 'ZE')] = 'PL'
angle_rules[('PM', 'PS')] = 'PL'
angle_rules[('PM', 'PM')] = 'PL'
angle_rules[('PM', 'PL')] = 'PL'

angle_rules[('PL', 'NL')] = 'ZE'
angle_rules[('PL', 'NM')] = 'PM'
angle_rules[('PL', 'NS')] = 'PL'
angle_rules[('PL', 'ZE')] = 'PL'
angle_rules[('PL', 'PS')] = 'PL'
angle_rules[('PL', 'PM')] = 'PL'
angle_rules[('PL', 'PL')] = 'PL'



position_rules = dict()
position_rules[('NL', 'NL')] = 'NL'
position_rules[('NL', 'NM')] = 'NL'
position_rules[('NL', 'NS')] = 'NL'
position_rules[('NL', 'ZE')] = 'NL'
position_rules[('NL', 'PS')] = 'NL'
position_rules[('NL', 'PM')] = 'NM'
position_rules[('NL', 'PL')] = 'ZE'

position_rules[('NM', 'NL')] = 'NL'
position_rules[('NM', 'NM')] = 'NL'
position_rules[('NM', 'NS')] = 'NL'
position_rules[('NM', 'ZE')] = 'NL'
position_rules[('NM', 'PS')] = 'NM'
position_rules[('NM', 'PM')] = 'ZE'
position_rules[('NM', 'PL')] = 'PM'

position_rules[('NS', 'NL')] = 'NL'
position_rules[('NS', 'NM')] = 'NL'
position_rules[('NS', 'NS')] = 'NL'
position_rules[('NS', 'ZE')] = 'NM'
position_rules[('NS', 'PS')] = 'ZE'
position_rules[('NS', 'PM')] = 'PM'
position_rules[('NS', 'PL')] = 'PB'

position_rules[('ZE', 'NL')] = 'NL'
position_rules[('ZE', 'NM')] = 'NL'
position_rules[('ZE', 'NS')] = 'NM'
position_rules[('ZE', 'ZE')] = 'ZE'
position_rules[('ZE', 'PS')] = 'PM'
position_rules[('ZE', 'PM')] = 'PL'
position_rules[('ZE', 'PL')] = 'PL'

position_rules[('PS', 'NL')] = 'NL'
position_rules[('PS', 'NM')] = 'NM'
position_rules[('PS', 'NS')] = 'ZE'
position_rules[('PS', 'ZE')] = 'PM'
position_rules[('PS', 'PS')] = 'PL'
position_rules[('PS', 'PM')] = 'PL'
position_rules[('PS', 'PL')] = 'PL'

position_rules[('PM', 'NL')] = 'NM'
position_rules[('PM', 'NM')] = 'ZE'
position_rules[('PM', 'NS')] = 'PM'
position_rules[('PM', 'ZE')] = 'PL'
position_rules[('PM', 'PS')] = 'PL'
position_rules[('PM', 'PM')] = 'PL'
position_rules[('PM', 'PL')] = 'PL'

position_rules[('PL', 'NL')] = 'ZE'
position_rules[('PL', 'NM')] = 'PM'
position_rules[('PL', 'NS')] = 'PL'
position_rules[('PL', 'ZE')] = 'PL'
position_rules[('PL', 'PS')] = 'PL'
position_rules[('PL', 'PM')] = 'PL'
position_rules[('PL', 'PL')] = 'PL'